### ISSUE TITLE
Crash in AssetManager.kt

### ISSUE THREAD

**Issue by tanmayyy** [klarna/klarna-mobile-sdk#133]
**Describe the bug**
Users experiencing crashes with the Klarna In-App SDK when trying to render KlarnaOSMView

**To Reproduce**
Unable to reproduce. From stacktraces it occurs when trying to render KlarnaOSMView.

**Expected behavior**
Fatal Exception: java.lang.StackOverflowError: stack size 1043KB
       at com.klarna.mobile.sdk.a.i.a.a.b.getAnalyticsManager(AssetManager.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.d.a$a.a(a.java:1)
       at com.klarna.mobile.sdk.a.i.a.d.b.getAnalyticsManager(ConfigParser.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.a.b.getAnalyticsManager(AssetManager.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.d.a$a.a(a.java:1)
       at com.klarna.mobile.sdk.a.i.a.d.b.getAnalyticsManager(ConfigParser.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.a.b.getAnalyticsManager(AssetManager.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.d.a$a.a(a.java:1)
       at com.klarna.mobile.sdk.a.i.a.d.b.getAnalyticsManager(ConfigParser.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.a.b.getAnalyticsManager(AssetManager.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.d.a$a.a(a.java:1)
       at com.klarna.mobile.sdk.a.i.a.d.b.getAnalyticsManager(ConfigParser.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.a.b.getAnalyticsManager(AssetManager.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.d.a$a.a(a.java:1)
       at com.klarna.mobile.sdk.a.i.a.d.b.getAnalyticsManager(ConfigParser.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.a.b.getAnalyticsManager(AssetManager.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.d.a$a.a(a.java:1)
       at com.klarna.mobile.sdk.a.i.a.d.b.getAnalyticsManager(ConfigParser.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.a.b.getAnalyticsManager(AssetManager.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.d.a$a.a(a.java:1)
       at com.klarna.mobile.sdk.a.i.a.d.b.getAnalyticsManager(ConfigParser.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.a.b.getAnalyticsManager(AssetManager.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.d.a$a.a(a.java:1)
       at com.klarna.mobile.sdk.a.i.a.d.b.getAnalyticsManager(ConfigParser.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.a.b.getAnalyticsManager(AssetManager.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.d.a$a.a(a.java:1)
       at com.klarna.mobile.sdk.a.i.a.d.b.getAnalyticsManager(ConfigParser.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.a.b.getAnalyticsManager(AssetManager.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.d.a$a.a(a.java:1)
       at com.klarna.mobile.sdk.a.i.a.d.b.getAnalyticsManager(ConfigParser.kt:1)
       at com.klarna.mobile.sdk.a.g.c$a.a(SdkComponent.kt:1)
       at com.klarna.mobile.sdk.a.i.a.a.b.getAnalyticsManager(AssetManager.kt:1)
       at com.klarna.mobile.sdk.a.g.e.a(e.java:4)
       at com.klarna.mobile.sdk.a.g.e.a(e.java:1)
       at com.klarna.mobile.sdk.a.i.a.a.e.c(RemoteAssetManager.kt:4)
       at com.klarna.mobile.sdk.a.i.a.a.e.a(RemoteAssetManager.kt:2)
       at com.klarna.mobile.sdk.a.i.a.a.e$b.a(RemoteAssetManager.kt:37)
       at com.klarna.mobile.sdk.a.i.a.a.e$b.invoke(RemoteAssetManager.kt:1)
       at com.klarna.mobile.sdk.a.i.a.a.e$e.invokeSuspend(RemoteAssetManager.kt:31)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Device and version:**
 - Device: Mi Note 10 Lite, Galaxy Z Flip3, Zenfone 6, POCO X3, Redmi Note 9 Pro 
 - OS version: Android 11, Android 10
 - Klarna In-App SDK version - 2.1.3

**Merchant Name**
Vestiaire Collective

**Impact Level**
App crashes while user is browsing a Product. Very high impact.

**Additional context**
about 12 crashes since the rollout of the feature.

**Comment by NMGuner** [comment]
Hi @tanmayyy, thanks for reaching out. We faced a similar issue with another app due to obfuscation of some classes inside the SDK with their release/production builds. We prevented that with new consumer proguard rules in [last versions of the SDK](https://github.com/klarna/klarna-mobile-sdk/blob/master/CHANGELOG.md#android). We will take a look at the stacktrace and try to identify your case but I would really appreciate it if you could update the SDK to the latest version available and try to test this in your release build as those might fix this similar issue.

**Comment by tanmayyy** [comment]
Thanks @NMGuner , we are upgrading to the latest version 2.1.5 . Let us know if there are any other quick fixes? Should we have some proguard rules on our end as well? Is there a config to disable the analytics if it is causing the crashes?

**Comment by tanmayyy** [comment]
Update to 2.1.5 indeed fixed it, thanks!
