### ISSUE TITLE
Found crash issue when clicking on hyperlink text( ex. Terms & Condition)

### ISSUE THREAD

**Issue by Sridharan0** [klarna/klarna-mobile-sdk#62]
--------- beginning of crash
2020-10-17 20:41:47.064 8525-8525/com.wrinkleit.ecommerce.android.local E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wrinkleit.ecommerce.android.local, PID: 8525
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wrinkleit.ecommerce.android.local/com.klarna.mobile.sdk.core.natives.browser.ui.InternalBrowserActivity}: android.view.InflateException: Binary XML file line #80 in com.wrinkleit.ecommerce.android.local:layout/activity_internal_browser: Binary XML file line #80 in com.wrinkleit.ecommerce.android.local:layout/activity_internal_browser: Error inflating class com.klarna.mobile.sdk.core.natives.browser.ui.TintableImageView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.view.InflateException: Binary XML file line #80 in com.wrinkleit.ecommerce.android.local:layout/activity_internal_browser: Binary XML file line #80 in com.wrinkleit.ecommerce.android.local:layout/activity_internal_browser: Error inflating class com.klarna.mobile.sdk.core.natives.browser.ui.TintableImageView
     Caused by: android.view.InflateException: Binary XML file line #80 in com.wrinkleit.ecommerce.android.local:layout/activity_internal_browser: Error inflating class com.klarna.mobile.sdk.core.natives.browser.ui.TintableImageView
     Caused by: java.lang.ClassNotFoundException: com.klarna.mobile.sdk.core.natives.browser.ui.TintableImageView
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.view.LayoutInflater.createView(LayoutInflater.java:815)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:438)
        at android.app.Activity.setContentView(Activity.java:3324)
        at com.klarna.mobile.sdk.core.natives.browser.ui.InternalBrowserActivity.onCreate(InternalBrowserActivity.kt:4)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
2020-10-17 20:41:47.074 8525-8525/com.wrinkleit.ecommerce.android.local E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: com.klarna.mobile.sdk.core.natives.browser.ui.TintableImageView
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 30 more
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/widget/AppCompatImageView;
        	... 30 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.appcompat.widget.AppCompatImageView" on path: DexPathList[[zip file "/data/app/com.wrinkleit.ecommerce.android.local-EUcwhuxXXNl6S5rZ3fhPaw==/base.apk"],nativeLibraryDirectories=[/data/app/com.wrinkleit.ecommerce.android.local-EUcwhuxXXNl6S5rZ3fhPaw==/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 30 more

**Comment by Sridharan0** [comment]
If some one finds issue post it here.

**Comment by Sridharan0** [comment]
Since I'm implementing this feature in my old project I'm using old Android Support libraries only. Is there any possible way to fix this without migrating to androidX @NMGuner

**Comment by NMGuner** [comment]
Unfortunately no, the team has decided not to support Android Support libraries in the long-term.

**Comment by Sridharan0** [comment]
Okay thanks for your reply. @NMGuner
